resolver: lts-5.17
packages:
- location:
    git: https://github.com/j-mueller/virtual-hom
    commit: d5399f8d381055901c6da6dc38a7498cdc77655a
- '.'

compiler: ghcjs-0.2.0.20160315_ghc-7.10.2
compiler-check: match-exact
setup-info:
 ghcjs:
  source:
   ghcjs-0.2.0.20160315_ghc-7.10.2:
    url: "https://github.com/nrolland/ghcjs/releases/download/v.0.2.0.20160315/ghcjs-0.2.0.20160315.tar.gz"